"use strict";
const { contextBridge, ipcRenderer } = require("electron");

/* NOTE: this preload runs sandboxed — only "electron" plus a few Node builtins can
 * be required here. Local modules (e.g. ./audioArchive) must be reached over IPC,
 * otherwise the whole preload fails to load and window.a2n is undefined. */

contextBridge.exposeInMainWorld("a2n", {
  getConfig: () => ipcRenderer.invoke("config:get"),
  setConfig: (partial) => ipcRenderer.invoke("config:set", partial),
  listDevices: () => ipcRenderer.invoke("devices:list"),
  startRecord: (opts) => ipcRenderer.invoke("record:start", opts),
  stopRecord: () => ipcRenderer.invoke("record:stop"),
  openDir: (dir) => ipcRenderer.invoke("app:openDir", dir),
  chooseDir: () => ipcRenderer.invoke("app:chooseDir"),
  pickFile: (opts) => ipcRenderer.invoke("app:pickFile", opts),
  transcribeFile: (filePath) => ipcRenderer.invoke("file:transcribe", filePath),
  regenerateNotes: (opts) => ipcRenderer.invoke("notes:regenerate", opts),
  notesModels: () => ipcRenderer.invoke("notes:models"),
  renameSpeaker: (opts) => ipcRenderer.invoke("transcript:renameSpeaker", opts),
  archiveScan: () => ipcRenderer.invoke("archive:scan"),
  archiveRun: () => ipcRenderer.invoke("archive:run"),
  archivePresets: () => ipcRenderer.invoke("archive:presets"),
  speakersStatus: (opts) => ipcRenderer.invoke("speakers:status", opts),
  speakersDiarize: (opts) => ipcRenderer.invoke("speakers:diarize", opts),
  speakersSetName: (opts) => ipcRenderer.invoke("speakers:setName", opts),
  speakersMerge: (opts) => ipcRenderer.invoke("speakers:merge", opts),
  speakersAudition: (opts) => ipcRenderer.invoke("speakers:audition", opts),
  lifecycleStatus: () => ipcRenderer.invoke("lifecycle:status"),
  lifecycleKeepAlive: () => ipcRenderer.invoke("lifecycle:keepAlive"),
  lifecycleTouch: () => ipcRenderer.invoke("lifecycle:touch"),
  onLifecycle: (cb) => ipcRenderer.on("lifecycle", (_e, d) => cb(d)),
  onLevel: (cb) => ipcRenderer.on("level", (_e, d) => cb(d)),
  onPipeline: (cb) => ipcRenderer.on("pipeline", (_e, d) => cb(d)),
  onTranscript: (cb) => ipcRenderer.on("transcript", (_e, d) => cb(d)),
  onArchive: (cb) => ipcRenderer.on("archive", (_e, d) => cb(d)),
  powerStatus: () => ipcRenderer.invoke("power:status"),
  powerSetMode: (opts) => ipcRenderer.invoke("power:setMode", opts),
  queueList: () => ipcRenderer.invoke("queue:list"),
  queueRunNow: () => ipcRenderer.invoke("queue:runNow"),
  queueRemove: (opts) => ipcRenderer.invoke("queue:remove", opts),
  onPower: (cb) => ipcRenderer.on("power", (_e, d) => cb(d)),
  onQueue: (cb) => ipcRenderer.on("queue", (_e, d) => cb(d)),
  meetingStatus: () => ipcRenderer.invoke("meeting:status"),
  onMeeting: (cb) => ipcRenderer.on("meeting", (_e, d) => cb(d)),
  meetingsList: () => ipcRenderer.invoke("meetings:list"),
  meetingsOpen: (opts) => ipcRenderer.invoke("meetings:open", opts),
  modelsStatus: () => ipcRenderer.invoke("models:status"),
  modelsDownload: (opts) => ipcRenderer.invoke("models:download", opts),
  modelsDelete: (opts) => ipcRenderer.invoke("models:delete", opts),
  modelsSetEndpoint: (opts) => ipcRenderer.invoke("models:endpoint", opts),
  modelsOpenDir: () => ipcRenderer.invoke("models:openDir"),
  llmTest: (opts) => ipcRenderer.invoke("llm:test", opts),
  llmProviders: () => ipcRenderer.invoke("llm:providers"),
  onModels: (cb) => ipcRenderer.on("models", (_e, d) => cb(d)),
});
